spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8091